### ISSUE TITLE
Not work when leave the "Current Input Source" empty

### ISSUE THREAD

**Issue by heyeshuang** [xream/atom-vim-mode-plus-auto-ime#3]
Hello, I'm writing a script for Windows just like [input-source-switcher ](https://github.com/vovkasm/input-source-switcher) does. However, when I leave the "Current Input Source" empty, while don't use the ${source} expression, this addon doesn't work as expected. The error in the developer console is shown below.

> Error: Command failed: /usr/local/bin/issw
> ϵͳ�Ҳ���ָ����·����
> 
> 
> 
>     at ChildProcess.exithandler (child_process.js:223:12)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:885:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by xream** [comment]
Imo, you should write a script which accepts one string argument(the name of the input source).

Then replace all the `/usr/local/bin/issw` to your script file path.

**Comment by heyeshuang** [comment]
I managed to finish that [script](https://github.com/heyeshuang/ime_helper) and write a [post](https://heyeshuang.github.io/blog/2017/09/05/atom-vim-mode-auto-switch-ime/) for this. Thanks for your pkg!

**Comment by xream** [comment]
Good job man! I'll put the link in README.
